fixes: [docs/convert] methods
Features
    Cache.GetError: "Method for returning Cache.E"
    Convert: "New methods GetString, GetInt, GetError"

Fixes:
    Storage.AddDoc: "Now switches to the correct index after adding a new doc"
    Storage.Read: "No longer creates nil docs on read"
    Storage.Write: "No longer skips empty maps"

Tests:
    MultiDoc: "Tests for checking doc switch & add"